all:
  hosts:
    hostFront:
      vm_name: front
      ansible_user: <AZURE_USER>
      ansible_ssh_private_key_file: <PUBLIC_KEY>
      ansible_host: <FRONT_IP>
    hostBack:
      vm_name: back
      ansible_user: <AZURE_USER>
      ansible_ssh_private_key_file: <PUBLIC_KEY>
      ansible_host: <BACK_IP>
    hostDb:
      vm_name: database
      ansible_user: <AZURE_USER>
      ansible_ssh_private_key_file: <PUBLIC_KEY>
      ansible_host: <DATABASE_IP>
  children:
    frontend:
      hosts:
        hostFront:
          frontend_port: 8080
          backend_address: <BACK_IP>
          backend_port: 8080
    backend_replicaset:
      hosts:
        hostBack:
          replicaset_port: 8080
          database_master_address: 10.0.3.10
          database_master_port: 3036
          database_slave_address: 10.0.2.10
          database_slave_port: 3037
          database_user: admin
          database_password: password
    db_master:
      hosts:
        hostDb:
          database_port: 3036
          database_user: admin
          database_password: password
    db_slave:
      hosts:
        hostBack:
          database_port: 3037
          database_user: admin
          database_password: password
          master_database_address: 10.0.3.10
          master_database_port: 3036