all:
  hosts:
    hostFront:
      vm_name: front
      ansible_user: bartlomiejkrawczyk
      ansible_ssh_private_key_file: /home/bartlomiejkrawczyk/.ssh/1672691168_314986.pub
      ansible_host: 20.229.137.56
    hostBack:
      vm_name: back
      ansible_user: bartlomiejkrawczyk
      ansible_ssh_private_key_file: /home/bartlomiejkrawczyk/.ssh/1672691168_314986.pub
      ansible_host: 20.4.76.177
    hostDb:
      vm_name: database
      ansible_user: bartlomiejkrawczyk
      ansible_ssh_private_key_file: /home/bartlomiejkrawczyk/.ssh/1672691168_314986.pub
      ansible_host: 20.4.79.187
  children:
    frontend:
      hosts:
        hostFront:
          frontend_port: 8080
          backend_address: 20.4.76.177
          backend_port: 8080
    backend:
      hosts:
        localhost:
          parameters:
            - backend_port: 8079
              database_address: 20.4.79.187
              database_port: 3037
              database_user: admin
              database_password: password
              directory: first
            - backend_port: 8080
              database_address: 20.4.79.187
              database_port: 3036
              database_user: admin
              database_password: password
              directory: second
    nginx:
      hosts:
        localhost:
          nginx_port: 8078
          read_backend_address: 20.4.76.177
          read_backend_port: 8080
          write_backend_address: 20.4.76.177
          write_backend_port: 8079
    db_master:
      hosts:
        hostDb:
          database_port: 3036
          database_user: admin
          database_password: password
    db_slave:
      hosts:
        hostDb:
          database_port: 3037
          database_user: admin
          database_password: password
          master_database_address: 20.4.79.187
          master_database_port: 3036
