all:
  hosts:
    hostFront:
      vm_name: front
      ansible_user: bartlomiejkrawczyk
      ansible_ssh_private_key_file: /home/bartlomiejkrawczyk/.ssh/1672691168_314986.pub
      ansible_host: 20.229.137.56
    hostBack:
      vm_name: back
      ansible_user: bartlomiejkrawczyk
      ansible_ssh_private_key_file: /home/bartlomiejkrawczyk/.ssh/1672691168_314986.pub
      ansible_host: 20.4.76.177
    hostDb:
      vm_name: database
      ansible_user: bartlomiejkrawczyk
      ansible_ssh_private_key_file: /home/bartlomiejkrawczyk/.ssh/1672691168_314986.pub
      ansible_host: 20.4.79.187
  children:
    frontend:
      hosts:
        hostFront:
          frontend_port: 8080
          backend_address: 20.4.76.177
          backend_port: 8080
    backend_replicaset:
      hosts:
        hostBack:
          replicaset_port: 8080
          database_master_address: 10.0.3.10
          database_master_port: 3036
          database_slave_address: 10.0.2.10
          database_slave_port: 3037
          database_user: admin
          database_password: password
    db_master:
      hosts:
        hostDb:
          database_port: 3036
          database_user: admin
          database_password: password
    db_slave:
      hosts:
        hostBack:
          database_port: 3037
          database_user: admin
          database_password: password
          master_database_address: 10.0.3.10
          master_database_port: 3036
