all:
  hosts:
    hostFront:
      vm_name: front
      ansible_user: bartlomiejkrawczyk
      ansible_ssh_private_key_file: /home/bartlomiejkrawczyk/.ssh/1672758260_7211452.pub
      ansible_host: 20.23.235.183
    hostBack:
      vm_name: back
      ansible_user: bartlomiejkrawczyk
      ansible_ssh_private_key_file: /home/bartlomiejkrawczyk/.ssh/1672758260_7211452.pub
      ansible_host: 20.123.168.66
    hostDb:
      vm_name: database
      ansible_user: bartlomiejkrawczyk
      ansible_ssh_private_key_file: /home/bartlomiejkrawczyk/.ssh/1672758260_7211452.pub
      ansible_host: 20.23.238.213
  children:
    frontend:
      hosts:
        hostFront:
          frontend_port: 8080
          backend_address: 20.123.168.66
          backend_port: 8080
    backend:
      hosts:
        hostBack:
          parameters:
            - backend_port: 8080
              database_address: 10.0.3.10
              database_port: 3036
              database_user: admin
              database_password: password
              directory: first
    db_master:
      hosts:
        hostDb:
          database_port: 3036
          database_user: admin
          database_password: password

