---
# TODO: Load all machines from azure
# - hosts: localhost
#   tasks:
#     - name: Echo virtual machines
#       ansible.builtin.shell:
#         cmd: echo {{ item.name }}
#       loop: "{{ virtual_machine }}"
    
#     - name: Echo deployments per virtual machines
#       ansible.builtin.shell:
#         cmd: echo {{ item.0.name }} {{ item.1.type }}
#       with_subelements:
#         - "{{ virtual_machine }}"
#         - deploy

- hosts: 
  - all
  - localhost
  become: true
  pre_tasks:
    - name: Echo virtual machines
      ansible.builtin.shell:
        cmd: echo {{ backend_port }} {{ abc }}
    - name: Update repository index
      apt:
        update_cache: yes
    
    - name: Upgrade packages
      apt:
        upgrade: dist

- hosts: 
  - frontend
  become: true
  roles:
    - frontend

- hosts: 
  - backend
  - backend_replicaset
  become: true
  roles:
    - backend_base

- hosts: 
  - backend
  become: true
  roles:
    - backend

- hosts: 
  - backend_replicaset
  become: true
  roles:
    - backend_replicaset

- hosts: 
  - db_master
  - db_slave
  become: true
  roles:
    - db_base

- hosts:
  - db_master
  become: true
  roles:
    - db_master

- hosts:
  - db_slave
  become: true
  roles:
    - db_slave
