- name: Install curl
  apt:
    name: curl
    state: latest

- name: Install npm
  apt:
    name: npm
    state: latest

- name: Deploy frontend
  ansible.builtin.script:
    cmd: front.sh {{ backend_address }} {{ backend_port }} {{ frontend_port }}
